<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>$(NetVersion)</TargetFramework>
		<OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Heron.MudCalendar" Version="3.4.0" />
		<PackageReference Include="Microsoft.Agents.AI.Abstractions" Version="1.0.0-rc2" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.3" PrivateAssets="all" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.3" />
		<PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="10.0.3" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
		<PackageReference Include="MudBlazor" Version="8.15.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AICalendar.Shared\AICalendar.Shared.csproj" />
	</ItemGroup>

</Project>
